version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    REPO_URI: 316497517854.dkr.ecr.us-east-1.amazonaws.com/Testingpipeline
  # Optional: remove secrets-manager if not using
  # secrets-manager:
  #   ECR_PASSWORD: ecr-secret:password

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Logging in to $REPO_URI
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI
      - IMAGE_URI=$REPO_URI:$IMAGE_TAG
      - echo Image URI will be: $IMAGE_URI

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $IMAGE_URI
      - echo Build and push complete.

artifacts:
  files:
    - '**/*'
