version: 0.2

phases:
  install:
    commands:
      - echo Logging in to DockerHub using AWS Secrets Manager...
      - DOCKERHUB_SECRET=$(aws secretsmanager get-secret-value --secret-id dockerhub/creds --query SecretString --output text)
      - DOCKERHUB_USERNAME=$(echo "$DOCKERHUB_SECRET" | jq -r .username)
      - DOCKERHUB_PASSWORD=$(echo "$DOCKERHUB_SECRET" | jq -r .password)
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 316497517854.dkr.ecr.us-east-1.amazonaws.com
      - export IMAGE_TAG=latest
      - export IMAGE_URI=316497517854.dkr.ecr.ap-south-1.amazonaws.com/application:$IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI

artifacts:
  files:
    - '**/*'
